// src/components/DeleteConfirmation.tsx
import * as React from "react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { authClient } from "@/lib/auth-client"
import { translations } from "@/i18n/constants"
import type { Locale } from "@/i18n/constants"
import { localizeUrl } from "@/i18n/utils"

interface DeleteConfirmationProps {
  locale?: Locale
}

export function DeleteConfirmation({ locale = "en" }: DeleteConfirmationProps) {
  const [open, setOpen] = React.useState(false)
  const [isDeleting, setIsDeleting] = React.useState(false)
  const [error, setError] = React.useState<string | null>(null)

  const t = translations[locale] || translations.en

  const handleDelete = () => {
    setError(null)
    setOpen(true)
  }

  const confirmDelete = async () => {
    try {
      setError(null)
      setIsDeleting(true)
      await authClient.deleteUser()
      const signInUrl = localizeUrl("/sign-in", locale)
      window.location.href = signInUrl
    } catch (err) {
      setError(err instanceof Error ? err.message : t.account.deleteFailed)
    } finally {
      setIsDeleting(false)
    }
  }

  const cancelDelete = () => {
    setError(null)
    setOpen(false)
  }

  return (
    <div className="relative">
      {error && (
        <p className="text-sm text-destructive mt-2">{error}</p>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          <Button variant="destructive" size="sm" onClick={handleDelete}>
            {t.account.deleteAccount}
          </Button>
        </DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t.account.deleteAccount}</DialogTitle>
            <DialogDescription>
              {t.account.areYouSure}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={cancelDelete}
              disabled={isDeleting}
            >
              {t.account.no}
            </Button>
            <Button
              variant="destructive"
              onClick={confirmDelete}
              disabled={isDeleting}
            >
              {isDeleting ? t.account.deleting : t.account.yes}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// src/components/DeleteConfirmation.svelte
<script lang="ts">
  import {Button} from "@/components/primitives/button";
  import {authClient} from "@/lib/auth-client";
  import {translations} from "@/i18n/constants";
  import type {Locale} from "@/i18n/constants";
  import {localizeUrl} from "@/i18n/utils";

  export let locale: Locale = "en";

  let showConfirmation = false;
  let isDeleting = false;
  let error: string | null = null;

  const t = translations[locale] || translations.en;

  function handleDelete() {
    error = null;
    showConfirmation = true;
  }

  async function confirmDelete() {
    try {
      error = null;
      isDeleting = true;
      await authClient.deleteUser();
      const signInUrl = localizeUrl("/sign-in", locale);
      window.location.href = signInUrl;
    } catch (err) {
      error = err instanceof Error ? err.message : t.account.deleteFailed;
    } finally {
      isDeleting = false;
    }
  }

  function cancelDelete() {
    error = null;
    showConfirmation = false;
  }
</script>

<div class="relative">
  {#if error}
    <p class="text-sm text-destructive mt-2">{error}</p>
  {/if}

  {#if !showConfirmation}
    <Button variant="destructive" size="sm" onclick={handleDelete}>
      {t.account.deleteAccount}
    </Button>
  {:else}
    <div class="flex items-center gap-2">
      <span class="text-sm text-gray-700">
        {t.account.areYouSure}
      </span>
      <Button
        variant="destructive"
        size="sm"
        onclick={confirmDelete}
        disabled={isDeleting}
      >
        {#if isDeleting}{t.account.deleting}{:else}{t.account.yes}{/if}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onclick={cancelDelete}
        disabled={isDeleting}
      >
        {t.account.no}
      </Button>
    </div>
  {/if}
</div>
