// src/components/PasswordField.tsx
import * as React from "react";
import {Eye, EyeOff, Lock} from "lucide-react";
import {Input} from "@/components/ui/input";
import {cn} from "@/lib/utils";

interface PasswordFieldProps extends React.InputHTMLAttributes<HTMLInputElement> {
  className?: string;
}

export function PasswordField({className, ...props}: PasswordFieldProps) {
  const [showPassword, setShowPassword] = React.useState(false);

  return (
    <div
      className={cn(
        "focus-within:ring-ring relative flex items-center rounded-md border pl-2 focus-within:ring-1",
        className
      )}
    >
      <Lock className="text-muted-foreground mr-1 h-5 w-5" />
      <Input
        {...props}
        type={showPassword ? "text" : "password"}
        className="border-0 bg-transparent pr-10 shadow-none focus-visible:ring-0 dark:bg-transparent"
      />
      <button
        type="button"
        className="text-muted-foreground hover:text-foreground absolute right-3"
        onClick={() => setShowPassword(!showPassword)}
        aria-label={showPassword ? "Hide password" : "Show password"}
      >
        {showPassword ? (
          <EyeOff className="h-4 w-4" />
        ) : (
          <Eye className="h-4 w-4" />
        )}
      </button>
    </div>
  );
}

// src/components/PasswordField.svelte
<script lang="ts">
  import {Input} from "@/components/primitives/input";
  import Eye from "@lucide/svelte/icons/eye";
  import EyeOff from "@lucide/svelte/icons/eye-off";
  import Lock from "@lucide/svelte/icons/lock";
  import {cn} from "@/lib/utils";

  export let value = "";
  export let placeholder = "Password";
  export let required = false;
  export let className = "";

  let showPassword = false;
  export let name = "password";

  const togglePasswordVisibility = () => {
    showPassword = !showPassword;
  };
</script>

<div
  class={cn(
    "relative flex items-center rounded-md border focus-within:ring-1 focus-within:ring-ring px-2",
    className,
  )}
>
  <Lock class="h-5 w-5 text-muted-foreground" />
  <Input
    type={showPassword ? "text" : "password"}
    {placeholder}
    class="border-0 focus-visible:ring-0 shadow-none bg-transparent dark:bg-transparent"
    {name}
    bind:value
    {required}
  />
  <button
    type="button"
    on:click={togglePasswordVisibility}
    class="focus:outline-none"
    aria-label={showPassword ? "Hide password" : "Show password"}
    aria-pressed={showPassword}
  >
    {#if showPassword}
      <EyeOff class="h-5 w-5 text-muted-foreground" />
    {:else}
      <Eye class="h-5 w-5 text-muted-foreground" />
    {/if}
  </button>
</div>
